### ISSUE TITLE
[fastproxy] after update from 3.3.2 to 3.3.3 some pages do not work

### ISSUE THREAD

**Issue by wollomatic** [traefik/traefik#11507]
### Welcome!

- [x] Yes, I've searched similar issues on [GitHub](https://github.com/traefik/traefik/issues) and didn't find any.
- [x] Yes, I've searched similar issues on the [Traefik community forum](https://community.traefik.io) and didn't find any.

### What did you do?

First, Traefik works as expected while the experimental fastProxy feature is disabled.

But when I have
```
experimental:
  fastProxy:
    debug: true
```
configured in the static configuration file, I get blank pages with some services. For example, Gatus and Grafana won't work. The Traefik dashboard works as expected and shows no errors or anomalies. The malfunctioning services are listed as running with no errors.

The error occurs only with Traefik 3.3.3. It worked with fastProxy enabled with version 3.3.2.

### What did you see instead?

The browser shows a blank page/timeout

![Image](https://github.com/user-attachments/assets/7c07ce68-f2c3-4476-87c8-bb44be4a8dcd)

### What version of Traefik are you using?

```
Version:      3.3.3
Codename:     saintnectaire
Go version:   go1.23.5
Built:        2025-01-31T14:55:01Z
OS/Arch:      linux/amd64
```

### What is your environment & configuration?

```yaml
log:
#  level: DEBUG
  level: INFO
#accessLog:
#  filePath: /logs/access.log
#  format: json
#  fields:
#    headers:
#      defaultMode: keep
providers:
  docker:
    exposedByDefault: false
#    endpoint: 'unix:///var/run/docker.sock' # für Betrieb ohne Docker Socket Proxy
    endpoint: 'tcp://dockerproxy:2375'
    network: traefik_proxy
  file:
    directory: /etc/traefik/dynamic
    watch: true
api:
  dashboard: true
  insecure: true
ping:
  entryPoint: web
entryPoints:
  web:
    address: ':80'
    http:
      redirections:
        entryPoint:
          to: ':443'
          scheme: https
  web-secure:
    address: ':443'
    http3: false
    http:
      encodeQuerySemicolons: true
      middlewares:
#        - autodetectContenttype@file
        - default-inflightreq@file
    transport:
      respondingTimeouts:
        readTimeout: 15m
        writeTimeout: 15m
        idleTimeout: 15m
certificatesResolvers:
  default:
    acme:
      email: *******
      storage: /etc/traefik/ACME/acme.json
      tlsChallenge: {}
  acmedns:
    acme:
      email: *******
      storage: /etc/traefik/ACME/acmedns.json
#       caServer: 'https://acme-staging-v02.api.letsencrypt.org/directory' # Staging, zum Testen Kommentar entfernen
      dnsChallenge:
        provider: *******
        delayBeforeCheck: 1s
        resolvers:
          - "1.1.1.1:53"
          - "8.8.8.8:53"
experimental:
  fastProxy:
    debug: true
metrics:
  prometheus:
    manualRouting: true
    buckets:
      - 0.1
      - 0.3
      - 1.2
      - 5
```

### If applicable, please paste the log output in DEBUG level

(no relevant log output even in DEBUG mode)

**Comment by kevinpollet** [comment]
Hello @wollomatic and thanks for raising this issue,

If you or any community member can help us find verified steps to reproduce the issue, we would love the help.

**Comment by wollomatic** [comment]
While I can't reproduce the issue with a small traefik/whoami image, I examined the requests to our `twinproduction/gatus` container with burp suite.

Small HTML pages are no problem, but I run into the issue while requesting js files: Without fastProxy everything looks great:

![Image](https://github.com/user-attachments/assets/2e2c4b2b-e9a3-4069-ad88-bfdee3c4a543)

But with fastProxy enabled the content seems corrupted/compressed/whatever:

![Image](https://github.com/user-attachments/assets/4be1b2d2-0cf8-4299-960f-ac5bf9688c16)

Also, the response needed about 15 seconds.

The docker-compose.yaml ist quite boring:
```
services:
  gatus:
    image: ghcr.io/twin/gatus:v5.15.0
    restart: always
    init: true
    depends_on:
      - postgres
    read_only: true
    user: 65534:65534
    mem_limit: 8GB
    environment:
      - ... # skipped
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.gatus.entrypoints=web-secure"
      - "traefik.http.routers.gatus.rule=Host(`*****.de`)"
      - "traefik.http.routers.gatus.tls=true"
      - "traefik.http.routers.gatus.tls.certresolver=default"
      - "traefik.http.routers.gatus.middlewares=default-ratelimit@file,secHeaders@file"
      - "traefik.http.routers.gatus.service=gatus"
      - "traefik.http.services.gatus.loadbalancer.server.port=8080"
      # block metrics endpoint for external access
      - "traefik.http.routers.gatus-metrics.rule=Host(`*****.de`)&&PathPrefix(`/metrics`)"
      - "traefik.http.routers.gatus-metrics.tls=true"
      - "traefik.http.routers.gatus-metrics.tls.certresolver=default"
      - "traefik.http.routers.gatus-metrics.middlewares=default-ratelimit@file,secHeaders@file"
      - "traefik.http.routers.gatus-metrics.service=noop@internal" # 418 I'm a teapot
    volumes:
     - ./config:/config:ro
    networks:
      - traefik_proxy
      - postgres
# [...]
```

**Comment by wollomatic** [comment]
I can reproduce it on my homelab environment. File size doesn't seem to be the problem. My static hugo blog works, my comentario instance not.

**Comment by douyux** [comment]
I think this issue related to https://github.com/traefik/traefik/pull/11458, maybe we should check chunked response before no content-length header response

**Comment by kevinpollet** [comment]
Hello,

We opened https://github.com/traefik/traefik/pull/11514.

Thanks @wollomatic and @douyux for the help!

**Comment by strausmann** [comment]
How do you do?

I also have considerable problems with 3.3.3. At first I did not associate it with Traefik. Some services like Sonarr, Vaultwarden, Fleet, Snipe-IT, seemed to work without problems.

But then I noticed that Snipe-IT, for example, displays strange numbers in the top left-hand corner.

Speedtest Tool “linuxserver/speedtest-tracker:latest” only displayed a white page with 1b60 at the top left.

After seeing that the latest version of Traefik is a week old, I briefly wondered when these problems started. So I went back down to version 3.3.2 and suddenly everything worked again.

I also use the FASTPROXY feature.

I also tried the version traefik/traefik:experimental-v3.3, but this version only supports.

**Comment by strausmann** [comment]
![Image](https://github.com/user-attachments/assets/f33815d9-3856-4edb-aff3-08f7547c6ca1)

**Comment by wollomatic** [comment]
Hi @strausmann,

as I see, the fix is still to review and so it is not merged into the traefik:experimental-v3.3 yet. I would suggest disabling the fastproxy feature until the fix is deployed.

**Comment by strausmann** [comment]
I'm currently back to 3.3.2 for now and happy with it, feel free to let me know if you want me to test the fix.

**Comment by nmengin** [comment]
Hey @strausmann,

Thanks for the proposition.
We'll keep you updated as soon as the PR is merged to allow you to give it a try.

**Comment by wollomatic** [comment]
Hi @kevinpollet, I can confirm: It works. Thank you!

**Comment by Power2All** [comment]
It's still not working.
Used v3.3.3 via Dockerhub, it shows the error.
Is there a fix still coming ? I see a lot of "2000" in my response, and breaks most websites with Javascript right now.

**Comment by kevinpollet** [comment]
Hello @Power2All,

Maybe you are facing a different issue.
Could you please open a new issue describing the problem with a minimal reproducible use case if possible?
